# http://about.travis-ci.org/docs/user/selenium-setup/
language: ruby
rvm:
  - 1.9.2
before_script:
  - "mv config/database.travis.yml config/database.yml"
  - sh -e /etc/init.d/xvfb start
bundler_args: --without development
script: "bundle exec rake travis"
branches:
  only:
    - master
    - staging
notifications:
  recipients:
    - tobi@rngtng.com
