rvm:
  - 1.9.2
before_script:
  - "mv config/database.travis.yml config/database.yml"
  - "mysql -e 'create database nups_test;' >/dev/null"
script: "bundle exec rake db:migrate test spec"
branches:
  only:
    - delivery
notifications:
  recipients:
    - tobi@rngtng.com
