---
method: smtp
host: www2.multiadmin.de:8080
smtp_settings:
  :port: 25
  :domain: "c-art-web.de"
  :user_name: "todo@c-art-web.de"
  :password: ""
  :address: "smtp.c-art-web.de"
  :authentication: :plain
  :enable_starttls_auto: false